# Generated by Django 5.2.1 on 2025-05-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nombre', models.CharField(max_length=100)),
                ('contrasena', models.CharField(default='', max_length=128)),
                ('edad', models.IntegerField(default=18, null=True)),
                ('sexo', models.CharField(blank=True, max_length=10)),
                ('peso', models.FloatField(blank=True, default=65, help_text='Peso en kilogramos')),
                ('altura', models.FloatField(blank=True, default=1.7, help_text='Altura en metros')),
                ('antecedentes', models.TextField(blank=True, help_text='Antecedentes médicos (opcional)')),
                ('is_active', models.BooleanField(default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acetona', models.FloatField()),
                ('resultado', models.CharField(max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.usuario')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
