# Generated by Django 5.2.1 on 2025-05-09 09:46

from django.db import migrations,models

def set_temp_passwords(apps, schema_editor):
    Usuario = apps.get_model('sensores', 'Usuario')
    for user in Usuario.objects.all():
        user.password = 'temp_password'  # Cambia esto después
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('sensores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='temp', max_length=128),
            preserve_default=False,
        ),
        migrations.RunPython(set_temp_passwords),
    ]
